bandwidth:
- 0.23
- 0.23
- 0.23
- 0.23
- 0.23
- 0.23
- 0.23
- 0.23
- 0.23
- 0.23
- 0.23
- 0.6
- 1.0
- 2.0
base_filename_in: MWR_LIS_A
base_filename_out: MWR_1C01_0-250-1001-75113006_A
beamwidth:
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
channels_ok:
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
filename_scheme: rpg
freq_shift:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
input_directory: add full directory path here
ir_bandwidth: .nan
ir_beamwidth: .nan
ir_wavelength: .nan
meas_constructor: from_rpg
n_sidebands: 1
nc_attributes:
  date_of_last_absolute_calibration: '2021-12-31 23:59:59'
  date_of_last_covariance_matrix: '2021-12-31 23:59:59'
  institution: ISPL
  instrument_calibration_status: calibrated
  instrument_generation: HATPRO G1-5
  instrument_history: to_be_specified
  instrument_hw_id: ''
  instrument_id: A
  instrument_manufacturer: RPG
  instrument_model: HATPRO
  ir_instrument_fabrication_year: TBC
  ir_instrument_manufacturer: ''
  ir_instrument_model: ''
  met_instrument_fabrication_year: ''
  met_instrument_manufacturer: ''
  met_instrument_model: ''
  principal_investigator: Remote_Sensing_Group
  site_location: LISA_P7,FRANCE
  type_of_automatic_calibrations: calibration with ambient temperature target and
    noise diode
  wigos_station_id: 0-250-1001-75113006
output_directory: add full directory path here
reader: reader_rpg
station_altitude: 55.0
station_latitude: 48.8277
station_longitude: 2.3806
