base_filename_in: MWR_LIN_A
base_filename_out: MWR_1C01_0-20000-0-10393_A
filename_scheme: radiometrics
input_directory: add full directory path here
meas_constructor: from_radiometrics
nc_attributes:
  date_of_last_absolute_calibration: '2021-12-31 23:59:59'
  date_of_last_covariance_matrix: '2021-12-31 23:59:59'
  institution: DWD
  instrument_calibration_status: calibrated
  instrument_generation: MP
  instrument_history: to_be_specified
  instrument_hw_id: 3263A
  instrument_id: A
  instrument_manufacturer: Radiometrics
  instrument_model: MP-3000A
  ir_instrument_fabrication_year: TBC
  ir_instrument_manufacturer: TBC
  ir_instrument_model: TBC
  met_instrument_fabrication_year: TBC
  met_instrument_manufacturer: TBC
  met_instrument_model: TBC
  principal_investigator: Remote Sensing Group
  site_location: LINDENBERG,GERMANY
  type_of_automatic_calibrations: gain calibration with ambient temperature target
    and noise diode
  wigos_station_id: 0-20000-0-10393
output_directory: add full directory path here
reader: reader_radiometrics
station_altitude: 123.0
station_latitude: 52.21
station_longitude: 14.12
